extra:
  consent:
    cookies:
      analytics:
        checked: false
        name: Google Analytics
      github:
        checked: false
        name: GitHub
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.escapeall:
    hardbreak: true
    nbsp: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
repo_url: https://github.com/matt1432/nixos-pcsd
site_name: NixOS-pcsd
theme:
  features:
  - content.code.copy
  - content.code.select
  font:
    text: Noto Sans
  name: material
  palette:
  - media: (prefers-color-scheme)
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - accent: blue
    media: '(prefers-color-scheme: dark)'
    primary: deep purple
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
