#!/usr/bin/env -S nix develop .#update -c bash

COMMIT="$1"
ROOT_DIR="$(pwd)"

git_push() {
    if [[ "$COMMIT" == "--commit" ]]; then
        (
            cd "$ROOT_DIR" || return
            git config --global user.name 'Updater'
            git config --global user.email 'robot@nowhere.invalid'
            git remote update

            alejandra .
            git add .

            git commit -m "$1"
            git push
        )
    else
        echo "$1"
    fi
}

updateNpmDepsHash() {
    file="$ROOT_DIR/pkgs/pcs-web-ui/npmDepsHash.nix"
    npm_hash="$(nix build .#pcs-web-ui |& sed -n 's/.*got: *//p')"

    if [[ "$npm_hash" != "" ]]; then
        {
            echo '# This file was autogenerated. DO NOT EDIT!'
            echo "\"$npm_hash\""
        } >"$file"

        echo "updated npmDepsHash"
    else
        echo "npmDepsHash is already up to date"
    fi
}

updateRubyDeps() {
    updateGems
    git_push "chore: update ruby deps"
}

getLatestTag() {
    owner="$1"
    repo="$2"

    cd /tmp || return
    git clone "https://github.com/$owner/$repo" &> /dev/null
    cd "$repo" || return
    tag=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=2) | sort -r | head -n 1)
    cd ..
    rm -rf "$repo" &> /dev/null

    echo "$tag"
}

updatePackage() {
    nix flake update

    owner="$1"
    repo="$2"
    file="$ROOT_DIR/pkgs/$repo/src.nix"

    current_version=$(nix eval --json --file "$file" | jq -r .rev)
    new_version=$(getLatestTag "$owner" "$repo")

    if [[ "$new_version" != "$current_version" ]]; then
        hash=$(nix-prefetch-github "$owner" "$repo" --rev "$new_version" |
            jq -r .hash)

        {
            echo '# This file was autogenerated. DO NOT EDIT!'
            echo '{'
            echo "  owner = \"$owner\";"
            echo "  repo = \"$repo\";"
            echo "  rev = \"$new_version\";"
            echo "  hash = \"$hash\";"
            echo '}'
        } >"$file"

        # Update third party sources
        if [[ "$repo" == "pcs-web-ui" ]]; then
            updateNpmDepsHash
        fi

        git_push "ci: $repo $current_version -> $new_version"
    else
        echo "$repo is already up to date"
    fi
}

updateRubyDeps
updatePackage "ClusterLabs" "pacemaker"
updatePackage "ClusterLabs" "pcs-web-ui"
updatePackage "ClusterLabs" "resource-agents"
updatePackage "ClusterLabs" "pcs"
