name: Publish docs via GitHub Pages
on:
    workflow_dispatch:
    push:
        branches:
            - master

jobs:
    build:
        name: Deploy docs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout main
              uses: actions/checkout@v4

            - name: setup-nix
              uses: cachix/install-nix-action@v31
              with:
                  github_access_token: ${{ secrets.GITHUB_TOKEN }}
                  extra_nix_config: |
                      accept-flake-config = true

            - name: Deploy docs
              run: nix develop .#docs -c ghDeploy
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
